services:
  loged-landing:
    image: nginx:latest
    container_name: teste-landing
    restart: unless-stopped
    ports:
      - "9090:80" # porta interna, ser√° exposta pelo Nginx Proxy Manager
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
